---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:11
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: npm install
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run:
          name: Testing
          command: npm test
      - run:
          name: Publishing the latest website
          command: cd ./docusaurus/website && npm run publish-gh-pages
  node-8:
    <<: *test
    docker:
      - image: node:10
  cache:
    <<: *test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
          paths:
            - ~/cli/node_modules
            - ~/.npm
            - /usr/local/lib/node_modules

workflows:
  version: 2
  "@itchef/rg-cli":
    jobs:
      - node-10
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
