---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:11
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: npm install
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run:
          name: Testing
          command: npm test
  node-10:
    <<: *test
    docker:
      - image: node:10
  gh-pages:
    docker:
      - image: node:11
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Publishing the latest website
          command: |
            git config --global user.email "$GITHUB_USERNAME@users.noreply.github.com"
            git config --global user.name $AUTHOR_NAME
            echo "machine github.com login $GITHUB_USERNAME password $GITHUB_TOKEN" > ~/.netrc
            cd ./website && npm install && GIT_USER=$GIT_USER npm run publish

  cache:
    <<: *test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}
          paths:
            - ~/cli/node_modules
            - ~/.npm
            - /usr/local/lib/node_modules

workflows:
  version: 2
  "regauge":
    jobs:
      - node-latest
      - node-10
      - gh-pages:
          requires:
                - node-latest
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
